void showMenu();
void showTitle();
int getOption();
void selectMenuOption(int option);
void showGameModesMenu();
void selectGameModeOption(int option);
void quit();
void showRules();
void pause();
void showRanking();
void showGameWillStartMsg();
void casualMatch();
void manualMatch();
card configCardHand(card card1, string message);
bool isValidCard(card card1);
void cardInvalidMessage();