handStatus verifyThree(card agroup[], int quantCards);
handStatus verifyPair(card agroup[], int quantCards);
handStatus verifyFullHouse(card agroup[], int quantCards);
handStatus verifyFour(card agroup[], int quantCards);
handStatus verifyFlush(card agroup[], int quantCards);
handStatus verifyStraight(card agroup[], int quantCards);
handStatus verifyFullHouse(card agroup[], int quantCards);
handStatus verifyStraightFlush(card agroup[], int quantCards);
handStatus verifyRoyalFlush(card agroup[], int quantCards);
void copyArrayHandStatus (handStatus current[], handStatus* target, int quantHands);